name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ghdl:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download and extract repositories
      shell: powershell
      run: ./00_get_code.ps1

    - name: Download and setup MinGW
      shell: powershell
      run: ./01_mingw.ps1
